services:
  verifier-redis:
    image: redis:7.2.2
    container_name: verifier-redis
    restart: always
    expose:
      - 6380
    command: [ "redis-server", "--port", "6380" ]
    networks:
      - crset-network
    profiles: [ verifier ]

  verifier-backend:
    build: ./verifier-demo/server
    ports:
      - "3000:8080"
      - "8090:8090"
    volumes:
      - ./verifier-demo/server/data:/app/data
    environment:
      - REDIS_HOST=verifier-redis
      - REDIS_PORT=6380
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      - verifier-redis
    env_file:
      - .env
    networks:
      - crset-network
    profiles: [ verifier ]

  verifier-frontend:
    build:
      context: ./verifier-demo/client
      args:
        - VITE_BACKEND_HOST=localhost
        - VITE_BACKEND_PORT=3000
    ports:
      - "3001:8080"
    depends_on:
      - verifier-backend
    env_file:
      - .env
    environment:
      - VITE_BACKEND_HOST=localhost
      - VITE_BACKEND_PORT=3000
    networks:
      - crset-network
    profiles: [ verifier ]

  issuer-app:
    build:
      context: ./issuer-demo
    ports:
      - "3000:3000"
    volumes:
      - ./issuer-demo/data:/app/data
    environment:
      - ISSUER_BACKEND_HOST=host.docker.internal
      - ISSUER_BACKEND_PORT=5050
      - NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
    env_file:
      - .env
    networks:
      - crset-network
    profiles: [ issuer ]

networks:
  crset-network:
    name: crset-network
