version: "3.8"

services:
  issuer-redis:
    image: redis:7.2.2
    container_name: issuer-redis
    ports:
      - "6379:6379" # Host port 6379 maps to container port 6379
    command: ["redis-server", "--port", "6379"]

  verifier-redis:
    image: redis:7.2.2
    container_name: verifier-redis
    ports:
      - "6380:6380" # Host port 6380 maps to container port 6380
    command: ["redis-server", "--port", "6380"]
