/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ApplyForLoanImport } from "./routes/applyForLoan";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const ApplyForLoanRoute = ApplyForLoanImport.update({
  id: "/applyForLoan",
  path: "/applyForLoan",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/applyForLoan": {
      id: "/applyForLoan";
      path: "/applyForLoan";
      fullPath: "/applyForLoan";
      preLoaderRoute: typeof ApplyForLoanImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/applyForLoan": typeof ApplyForLoanRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/applyForLoan": typeof ApplyForLoanRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/applyForLoan": typeof ApplyForLoanRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/applyForLoan";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/applyForLoan";
  id: "__root__" | "/" | "/applyForLoan";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApplyForLoanRoute: typeof ApplyForLoanRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyForLoanRoute: ApplyForLoanRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/applyForLoan"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/applyForLoan": {
      "filePath": "applyForLoan.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
