import Head from "next/head";

export default function Page() {
  return (
      <>
      <Head>
          <title>Issuer Demo App</title>
          <meta name="description" content="Generated by create next app" />
      </Head>
    <div className="flex flex-col items-center justify-center h-screen space-y-4">
      <h1 className="text-2xl font-bold">Welcome to the Credential App</h1>
      <h4>
        Here you can issue an employee credential, view its status and revoke
        it.
      </h4>
    </div>
      </>
  );
}
